### ISSUE TITLE
关于exp中bypass io_vtable_check

### ISSUE THREAD

**Issue by m4p1e** [spineee/hctf#1]
```python
write_to(tls_addr+0x14f0,'a'*8)
```
师傅你这个地方应该是写 pointer_guard 值 ，应该是fs:[30h],为什么是0x14f0呢，是如何计算tls在内存上的分布呢? 希望师傅能够解答，不甚感谢！

**Comment by spineee** [comment]
时间久远，我也忘了，可能是search出来的？也不麻烦吧，先找到tls，然后把内存dump出来看看也行，反正不长。定位tls的话就在libc附近，长度好像是0x3000的一个块。

**Comment by m4p1e** [comment]
exp中，为什么tls会在got[1]指向的段上，师傅我想知道这个问题！

**Comment by spineee** [comment]
emmm，当时记得就是随便找了个指向tls的指针，没啥特别的意思。你要深究自己去看源码吧

**Comment by spineee** [comment]
close
